### ISSUE TITLE
Research expected prediction support in llama.cpp

### ISSUE THREAD

**Issue by vidas** [aifoundry-org/NekkoAPI#14]
We need to support `prediction` parameter in `/v1/chat/completions` API endpoint. OpenAI docs here: https://platform.openai.com/docs/api-reference/chat/create#chat-create-prediction)

Please research what is necessary for it to work in llama.cpp (if at all):
- what kind of arguments are used
- what types of models can support this
- does it give any real benefits (this parameter is intended as performance optimization and does not affect the result in any way).

Please attach your findings to this issue as comments.

**Comment by akxcv** [comment]
**Summary: Predicted Outputs are **only** supported by OpenAI**

As far as I can tell, Predicted Outputs are currently only supported by OpenAI and, specifically, `gpt-4o` and `gpt-4o-mini`. I could not find any other models that support this feature.

Well-known inference UI projects also do not yet support this feature. LiteLLM's support for this feature is scoped strictly to OpenAI's API.

With that said, it's probably a matter of time before other model developers implement this in their new models. But, until then, it's probably best to postpone the implementation.

The `prediction` parameter is currently quite simple. It is well-described with [examples](https://platform.openai.com/docs/guides/predicted-outputs) in OpenAI's documentation, but it looks something like this:

```js
{
  // ...
  prediction: {
    type: "content", // "content" is the only type currently supported by the API
    content: "<predicted output text>",
  },
}
```

The model will try to reuse as many tokens as possible from the prediction content, dismissing tokens it finds irrelevant. The work is still performed on every token of the prediction, meaning that predictions are more expensive when per-token billing is considered, but they do speed up the response considerably when used correctly.

A perfect use case of Predicted Outputs is asking the model to add some functionality to already existing code. The model will just reuse all the provided code, ideally dismissing 0 prediction tokens, and will only produce new tokens writing the code for new functionality.

**Comment by vidas** [comment]
Even negative result is a result. Thank you, @akxcv!

I'll reference this in `prediction` ticket.

**Comment by akxcv** [comment]
We should keep an eye on how support for this develops.
