### ISSUE TITLE
max_completion_tokens

### ISSUE THREAD

**Issue by Sergyenko** [aifoundry-org/NekkoAPI#2]
The user needs to control how long the generated response can be. By specifying max_completion_tokens, one can set the maximum number of tokens in the generated completion, ensuring that the output does not exceed a desired length. For instance, if the user wants a concise summary rather than a long essay, setting a lower max_completion_tokens helps maintain brevity.

OpenAI API Reference:
[OpenAI Completion Docs - max_tokens](https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_completion_tokens)

**Detailed Description of Parameters:**
	•	Type: integer
	•	Range: 1 to any upper limit defined by the model’s context window
	•	Default Value: Depending on the implementation, if not specified, it could default to the model’s maximum context window size minus the prompt tokens (e.g., max_completion_tokens = 256), or a sensible default like 256 tokens.

**Description:**
Defines the upper bound on the length of the generated response in tokens. Once the model has generated max_completion_tokens tokens, it will stop producing further output, even if no stop sequence is encountered.

**Behavior:**
	•	If max_completion_tokens is set too low, the model may produce only very short answers.
	•	If set very high, the model may produce unnecessarily long responses, potentially increasing costs and processing time.
	•	Combined with stop sequences and other parameters (temperature, top_p), it ensures that the generation remains under user control in terms of length, style, and content.

**Examples:**
	•	max_completion_tokens: 50: Limits the response to at most 50 tokens, useful for brief summaries.
	•	max_completion_tokens: 1000: Allows for more extended answers, potentially longer stories or detailed explanations.

**Comment by vidas** [comment]
Some notes for the record (to be used in docs?):
1. If `max_completion_tokens` together with prompt tokens exceeds context window size, `max_completion_tokens` will be automatically truncated. There is no need be be careful about maximum value and count prompt tokens (not trivial with arbitrary models) or interrogate the model about it's context window.
2. Default value is "infinite", i.e. no limit on token count. Completion will stop either when the context window is full or some other condition (eg. `stop`) is satisfied.
