### ISSUE TITLE
logprobs

### ISSUE THREAD

**Issue by damarcus88** [aifoundry-org/NekkoAPI#20]
**User Case:**
A user or developer may want to understand why the model chose certain tokens over others. By using logprobs, the user gains insight into the model’s decision-making process at each step. This can help with debugging, analyzing the model’s behavior, or building applications that rely on token-level probability distributions.

**OpenAI API Reference:**
[OpenAI Completion Docs - logprobs](https://platform.openai.com/docs/api-reference/chat/create#chat-create-logprobs)

Detailed Description of Parameters:
	•	Type: integer (or null)
	•	Range: Typically 0 to a positive integer (e.g., 5, 10, etc.)
	•	Default Value: null (no log probabilities are returned by default)

**Description:**
When logprobs is set to a positive integer n, the API returns the log probabilities of the chosen tokens as well as the n most likely alternative tokens at each generation step. The returned data includes:
	•	tokens: The tokens that were generated.
	•	token_logprobs: The log probabilities of each chosen token.
	•	top_logprobs: A list of dictionaries containing the n tokens with the highest log probabilities and their associated log probabilities at each token position.
	•	text_offset (if applicable): The position of each token in the response text.

**Behavior:**
	•	If logprobs is not specified (or is null), the response contains only the generated text without any probability information.
	•	If logprobs is set (e.g., logprobs: 5), the response includes additional fields that detail the probabilities for each generated token, along with the top 5 candidate tokens the model considered at each step.
	•	Accessing logprobs data can be computationally more expensive and may slightly slow down requests due to the extra information returned.

**Examples:**
	•	logprobs: 0 : Returns chosen tokens and their log probabilities, but does not include alternatives.
	•	logprobs: 5 : Returns chosen tokens with their log probabilities, as well as the top 5 tokens the model considered at each step.

**Comment by vidas** [comment]
One small nitpick - we don't return the `bytes` field (it repeats the token string in numbers). This can be addressed once we work on polishing chat completion responses.
