### ISSUE TITLE
response_format

### ISSUE THREAD

**Issue by damarcus88** [aifoundry-org/NekkoAPI#23]
**User Case:**
The user wants to ensure that the model’s response adheres to a specific output format, such as a well-formed JSON object or a response matching a given JSON schema. This parameter enables strict output formatting, which can be crucial when integrating model responses into systems that require structured data.

**OpenAI API Reference:**
[Chat Completion Docs - response_format](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format)

Detailed Description of Parameters:
	•	Type: object
	•	Optional: Yes

**Description:**
An object specifying the format in which the model must produce its output. It’s compatible with certain GPT-4 and GPT-3.5 Turbo models (e.g., GPT-4o, GPT-4o mini, GPT-4 Turbo, and any GPT-3.5 Turbo newer than gpt-3.5-turbo-1106).

The response_format object supports different type values to define the desired response format:
	1.	**"type": "json_object"**
Ensures the model’s response is valid JSON.
Important:
	•	You must explicitly instruct the model (via a system or user message) to produce JSON. If not, the model may return extraneous whitespace until max_tokens is reached, causing long-running requests.
	•	If the response is truncated (finish_reason: “length”), the JSON may be partially cut off.
	2.	**"type": "json_schema"**
Enables Structured Outputs by enforcing a given JSON schema. The model will attempt to produce JSON strictly adhering to the specified schema.
	•	Fields:
	•	json_schema: object (Required)
	•	name: string (Required) – A short, descriptive name of the response format.
	•	Allowed characters: a-z, A-Z, 0-9, underscore (_), dash (-)
	•	Maximum length: 64 characters
	•	description: string (Optional) – A textual description of what the response format is for, helping the model understand the response requirements.
	•	schema: object (Optional) – A JSON Schema object that the model’s output should match.
	•	strict: boolean or null (Optional, defaults to false) – If true, the model must adhere strictly to the provided schema. Only a subset of JSON Schema is supported in strict mode.
	3.	**"type": "text"**
The model outputs a plain text response without enforced structured formatting.

**Behavior:**
	•	If response_format is not provided, the model returns output as regular text without enforcing a particular format.
	•	If response_format is provided with "type": "json_object", the model’s response is expected to be valid JSON. The user should instruct the model to produce JSON, or risk incomplete output.
	•	If response_format is provided with "type": "json_schema", the model is expected to produce JSON conforming to the given schema. Enabling strict: true further enforces compliance but may limit the schema features available.
	•	If response_format is provided with "type": "text", the model returns a standard text response.

**Comment by vidas** [comment]
Some notes for the record

Main differences from OpenAI schema support:
1. `strict` field is ignored (in a backwards compatible way). OpenAI (when `strict` is true) refuses to handle requests for schemas with features they don't support (like `maxLenght` constraint for strings). We **do** support schema features not supported by OpenAI. We don't have to choose between "partially adhering to schema" or "failing", when we can fully enforce requested JSON schema.
2. `description` field is *not* forwarded to the model (this feature can only be implemented individually for each model).
3. The schema itself is *not* forwarded to the model and is only implemented at a sampler level.
4. Errors are more forgiving to the schema format. When something fails our errors are ~~less~~ not helpful or descriptive in comparison to the ones returned by OpenAI (this is doable and is left for the future).

In general, `"response_format": { type: "json_schema" }` (defined as Structured Outputs mode by OpenAI) can only be implemented on a per-model level, with custom prompts (or at least chat formats). Our implementation is implemented at the sampler level, i.e. it doesn't inform the model of the schema, but only enforces it mechanically when selecting completion tokens. Strangely, it does work!

I'd suggest to instruct the model to produce JSON and give it schema explicitly in the prompt even for `json_schema` mode. In other words - for the best result you should do it at the application level.
