### ISSUE TITLE
stream

### ISSUE THREAD

**Issue by damarcus88** [aifoundry-org/NekkoAPI#26]
**User Case:**
A user wants to receive the generated response incrementally rather than waiting for the entire response to be completed. By using the stream parameter, the model’s output can be returned as a series of partial responses (tokens), enabling developers to show a typing effect or provide the user with partial results sooner, improving the responsiveness of the application.

**OpenAI API Reference:**
[OpenAI Completion Docs - stream](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream)

Detailed Description of Parameters:
	•	Type: boolean
	•	Default Value: false

**Description:**
When stream is set to true, the API returns the response in chunks (partial tokens) as they are generated. When false, it returns the entire completion in a single response.

**Behavior:**
	•	stream = false: The user receives the full response only after it has been completely generated.
	•	stream = true: The user receives tokens as they are produced, allowing for real-time display of the model’s progress.

**Examples:**
	•	stream: true: Ideal for chat-like interfaces where the user sees tokens appear one by one.
	•	stream: false: Best when the complete response is needed before displaying to the user.

**Comment by vidas** [comment]
Streaming just works, verified the code and behavior, nothing additional to code here.

Will add tests in #15.
