### ISSUE TITLE
function_call (depricated)

### ISSUE THREAD

**Issue by damarcus88** [aifoundry-org/NekkoAPI#38]
**User Case:**
Allows you to instruct the model on how to handle or return function calls during a chat completion. This can range from disallowing function calls altogether, letting the model decide on its own, or forcing it to call a specific function.

OpenAI API Reference:
[Chat Completion Docs - function_call](https://platform.openai.com/docs/api-reference/chat/create#chat-create-function_call)

**Detailed Description of Parameters**
	•	Type: Either string or object

Parameter Values:
	•	String
	•	"none": The model will not call any function, producing a text response only.
	•	"auto": The model decides whether to output a standard message or call a function.
	•	Object
	•	{"name": "my_function"}: Forces the model to call the named function.

**Behavior**
	1.	If no functions are provided, function_call defaults to "none".
	2.	If functions are provided, function_call defaults to "auto".
	3.	When "none", the model consistently avoids function calls.
	4.	When "auto", the model uses its own logic to determine whether a function is needed.
	5.	When an object with a specific name is specified, the model must call that function in its response.

**Examples**
	•	String Example ("none")
	•	The model returns a textual reply only.
	•	String Example ("auto")
	•	The model might choose to either produce a message or call a function.
	•	Object Example
	•	{"name": "my_function"} forces a function call to "my_function".

**Comment by vidas** [comment]
Option "auto" has the same problems as `tool_choice: "auto"`. Will be solved there.
