### ISSUE TITLE
finish_reason (choices)

### ISSUE THREAD

**Issue by damarcus88** [aifoundry-org/NekkoAPI#40]
**User Case**

Indicates why the generation of a particular completion ended. This helps the user or developer understand if the model reached a stop sequence, ran out of tokens, or ended for any other reason (e.g., a function call).

**Reference**

[Chat Completion Docs – finish_reason](https://platform.openai.com/docs/api-reference/chat/object#chat/object-choices)

**Detailed Description of Parameters**
	•	Type: String
	•	Common Values:
	•	"stop": The model encountered a natural stopping point (often a stop sequence).
	•	"length": The model reached the maximum token limit (max_tokens) or context limit.
	•	"function_call" or "tools_call": The model’s output is a function call (in function-calling enabled scenarios).
	•	"content_filter" or other internal flags may appear in certain contexts.

**Behavior**
	•	This field helps determine if the model’s output was cut off. If the finish_reason is "length", it means the response could be incomplete.
	•	If the finish_reason is "stop", it indicates a complete or natural finishing point.

**Examples**
	•	"finish_reason": "stop": The response ended because it hit a user-defined or default stop condition.
	•	"finish_reason": "length": The output ended due to exceeding token limits.

**Comment by vidas** [comment]
Function calls are implemented as tool call transparently (almost) to the caller.
What this means, is that for function call returned `finish_reason` will be `"tool_calls"`.
This can be resolved by a couple of additional "backwards compatibility" clauses. Please advise.
