### ISSUE TITLE
index (choices)

### ISSUE THREAD

**Issue by damarcus88** [aifoundry-org/NekkoAPI#41]
**User Case**

When multiple choices are returned, each choice has a numerical index to help the developer identify and handle them in order. This is especially relevant if you requested n > 1.

**Reference**

[Chat Completion Docs – index](https://platform.openai.com/docs/api-reference/chat/object#chat/object-choices)

**Detailed Description of Parameters**
	•	Type: Integer
	•	Description: The position of the completion within the choices array.

**Behavior**
	•	Typically starts at 0 and increments by 1 for each choice.
	•	Useful for referencing and differentiating multiple completions in your application logic.

**Examples**
	•	For a single completion, the index will often be 0.
	•	For three completions, expect index to be 0, 1, and 2 respectively.

**Comment by vidas** [comment]
Until `n` is implemented, `index` is always `0`.
